name: Build corosync-qdevice

on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        release: "14.2"
        prepare: |
          pkg install -y git bash autoconf automake gmake gcc pkgconf libtool nss corosync3
        run: |
          mkdir build
          git clone https://github.com/corosync/corosync-qdevice.git src
          cd src
          git checkout v3.0.3
          export MAKE=gmake
          ./autogen.sh
          ./configure --disable-systemd --prefix=/opt/corosync-qdevice
          gmake clean
          gmake all
          gmake install DESTDIR=/home/runner/work/corosync-qdevice-freeBSD/corosync-qdevice-freeBSD/build
    - uses: actions/upload-artifact@v4
      with:
        name: corosync-qdevice
        path: build
