name: Build corosync-qdevice

on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: 'https://github.com/corosync/corosync-qdevice.git'
        ref: 'v3.0.3'
        path: 'src'
    - uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        release: "14.2"
        prepare: |
          pkg install -y git bash autoconf automake gmake gcc pkgconf libtool nss corosync3
        run: |
          mkdir build
          cd ./src
          export MAKE=gmake
          ./autogen.sh
          ./configure --disable-systemd --prefix=../build
          gmake clean
          gmake all
          cd ../build
          ls -al
    - uses: actions/upload-artifact@v4
      with:
        name: corosync-qdevice
        path: ./build
