name: Build corosync-qdevice

on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: 'corosync/corosync-qdevice'
        ref: 'v3.0.3'
        path: 'src'
    - uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        release: "14.2"
        prepare: |
          pkg install -y git bash autoconf automake gmake gcc pkgconf libtool nss corosync3
        run: |
          mkdir -p /opt/corosync-qdevice
          mkdir build
          cd src
          export MAKE=gmake
          ./autogen.sh
          ./configure --disable-systemd --prefix=/opt/corosync-qdevice
          gmake clean
          gmake all
          gmake install DESTDIR=../build
          ls -al /opt/corosync-qdevice
          ls -al ../build
    - uses: actions/upload-artifact@v4
      with:
        name: corosync-qdevice
        path: /opt/corosync-qdevice
